version: "3"
networks:
  gitea:
    external: false

volumes:
  gitea:
    external: false
    driver: local
  mysql:
    external: false
    driver: local

services:
  server:
    image: gitea/gitea:1.16.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=10.1.2.70:3306 # vpn client ip here
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - "3306:3306"
    networks:
      - gitea
    volumes:
      - mysql:/var/lib/mysql
